[build]
  command = "pnpm build:webapp"
  publish = "dist/webapp"
  ignore = "bash scripts/netlify-ignore-webapp.sh"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(self)"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
